Repository feelsantiago/mesa-computaria, pull requests merged in 2022-03, with the labels that each got.

#10 Create README.md
  README.md
Labels: enhancement

#13 [MC-12] Reamde team names
  README.md
Labels: bug

#18 [CI/CD] - Update CI/CD Pipeline
  .github/workflows/ci-pull-request.yml
  .github/workflows/ci.yml
  .github/workflows/firebase-hosting-merge.yml
  README.md
Labels: enhancement

#19 Deploy to master
  .github/workflows/ci-pull-request.yml
  .github/workflows/ci.yml
  .github/workflows/firebase-hosting-merge.yml
  README.md
Labels: enhancement

#32 [MC-29] - Add Thiago Santiago Information
  package-lock.json
  src/pages/home/index.html
Labels: feature

#33 [MC-26] - Create Component Page
  package-lock.json
  src/layouts/home.layout.html
  src/pages/components/index.html
  src/pages/components/main.js
  src/pages/components/main.test.js
  src/pages/components/style.scss
  vite.config.js
Labels: feature

#35 [MC-#14] - Create Text Input Component
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/scss/input-box.scss
  src/pages/components/index.html
  src/pages/components/main.js
  src/pages/components/main.test.js
  src/pages/components/style.scss
  src/pages/home/main.js
  src/pages/home/main.test.js
  src/services/tests/layout-provider.service.test.js
  src/utils/string.js
  src/utils/tests/string.test.js
Labels: feature

#36 [MC-15] - Create Password Input Component
  .github/codecov.yml
  package-lock.json
  package.json
  src/assets/fonts/biyrani/Biryani-Regular.ttf
  src/assets/fonts/im-fell-english/IMFellEnglish-Regular.ttf
  src/assets/fonts/noto-sans/NotoSans-Regular.ttf
  src/assets/scss/_variables.scss
  src/assets/scss/home-layout.scss
  src/assets/scss/input-box.scss
  src/assets/scss/input-password.scss
  src/assets/scss/style.scss
  src/pages/components/index.html
  src/pages/components/main.js
  src/pages/components/main.test.js
  src/pages/components/style.scss
  src/pages/home/main.js
  src/pages/home/main.test.js
  src/services/password-input.service.js
  src/services/tests/password-input.service.test.js
Labels: feature

#38 [MC-16] - Create Checkbox Component
  src/assets/scss/checkbox.scss
  src/pages/components/index.html
  src/pages/components/style.scss
Labels: feature

#49 [MC-24] - Create Dropdown Input Component
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/scss/dropdown.scss
  src/assets/scss/home-layout.scss
  src/components/dropdown.component.js
  src/components/tests/dropdown.component.test.js
  src/pages/components/index.html
  src/pages/components/main.js
  src/pages/components/style.scss
  vite.config.js
Labels: feature
