Repository feelsantiago/mesa-computaria, pull requests merged in 2022-04, with the labels that each got.

#50 [MC-48] - Alignment problems in the password box
  src/assets/scss/checkbox.scss
  src/assets/scss/input-password.scss
  src/pages/components/index.html
  src/pages/components/style.scss
Labels: bug, 0, Sprint 2

#39 [MC-21] Create Buttom Component
  package-lock.json
  src/assets/images/Icon-Jogos.png
  src/assets/images/Icon-Usuarios.png
  src/assets/scss/buttons.scss
  src/assets/scss/style.scss
  src/pages/components/index.html
  src/pages/components/style.scss
Labels: feature

#51 [MC-42] Create Component Logic Dropdown Input
  .eslintrc.json
  src/assets/scss/dropdown.scss
  src/components/dropdown.component.js
  src/components/tests/dropdown.component.test.js
  src/pages/components/index.html
  src/pages/components/main.js
  src/shared/erros/dropdow-option-not-found.erros.js
Labels: feature, 3, Sprint 2

#52 [MC-40] Create Component Logic Password Input
  src/assets/images/accept.png
  src/assets/images/cancel.png
  src/assets/scss/_variables.scss
  src/assets/scss/dropdown.scss
  src/assets/scss/home-layout.scss
  src/assets/scss/input-password.scss
  src/components/password.components.js
  src/components/tests/password.components.test.js
  src/pages/components/index.html
  src/pages/components/main.js
  src/pages/components/style.scss
  src/services/password-input.service.js
  src/services/tests/password-input.service.test.js
Labels: feature, 3, Sprint 2

#57 [MC-43] Create logic component checkbox
  src/assets/scss/checkbox.scss
  src/assets/scss/input-password.scss
  src/components/checkbox.component.js
  src/components/component.js
  src/components/dropdown.component.js
  src/components/tests/checkbox.component.test.js
  src/components/tests/dropdown.component.test.js
  src/components/tests/main.test.js
  src/layouts/home.layout.html
  src/pages/components/index.html
  src/pages/components/main.js
  src/pages/components/style.scss
  src/services/layout-provider.service.js
  src/services/tests/layout-provider.service.test.js
  src/utils/errors.js
  vite.config.js
Labels: feature

#55 [MC-45] Create Logic Component Input
  package-lock.json
  package.json
  src/assets/scss/checkbox.scss
  src/components/input-components.js
  src/components/tests/email-input.components.test.js
  src/components/tests/text-input.components.test.js
  src/components/text-input-email.components.js
  src/components/text-input.components.js
  src/pages/components/index.html
  src/pages/components/main.js
  src/pages/components/style.scss
  src/shared/erros/text-input-email.erros.js
Labels: feature, 3 points, Sprint 2
